# Generated by Django 4.1.4 on 2022-12-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customers',
        ),
    ]
