# Generated by Django 4.1.4 on 2022-12-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkbay',
            name='bay_time',
        ),
    ]
