# Generated by Django 4.1.4 on 2022-12-23 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookparking',
            name='booking_for',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
