# Generated by Django 4.1.4 on 2022-12-23 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpark', '0002_bookparking_booking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookparking',
            name='booking_for',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
