# Generated by Django 4.1.4 on 2022-12-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpark', '0003_alter_bookparking_booking_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookparking',
            name='Booked_bay_number',
            field=models.IntegerField(default=0),
        ),
    ]
