# Generated by Django 4.1.4 on 2022-12-23 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpark', '0004_bookparking_booked_bay_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookparking',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.utcnow),
        ),
    ]
