# Generated by Django 4.1.4 on 2022-12-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carpark', '0005_alter_bookparking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookparking',
            name='Booked_bay_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Carpark.parkbay'),
        ),
    ]
