# Generated by Django 4.1.4 on 2022-12-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpark', '0007_alter_bookparking_booked_bay_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkbay',
            name='bay_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookparking',
            name='booking_for',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='parkbay',
            name='bay_number',
            field=models.IntegerField(default=0),
        ),
    ]
