# Generated by Django 4.1.4 on 2022-12-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpark', '0008_parkbay_bay_id_alter_bookparking_booking_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkbay',
            name='bay_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
