# Generated by Django 4.1.4 on 2022-12-24 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpark', '0011_remove_parkbay_id_alter_parkbay_bay_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookParking',
            new_name='BayBooked',
        ),
        migrations.AlterField(
            model_name='parkbay',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
    ]
