# Generated by Django 4.1.4 on 2022-12-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carpark', '0012_rename_bookparking_baybooked_alter_parkbay_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BayBooked',
            new_name='BayBooking',
        ),
        migrations.RenameField(
            model_name='baybooking',
            old_name='Booked_bay_number',
            new_name='booked_bay_number',
        ),
        migrations.RenameField(
            model_name='parkbay',
            old_name='Booked',
            new_name='booked',
        ),
    ]
