# Generated by Django 4.1.4 on 2022-12-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpark', '0014_parkbay_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkbay',
            name='customer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
