# Generated by Django 4.1.4 on 2022-12-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpark', '0002_remove_parkbay_bay_time'),
        ('customers', '0003_rename_customers_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('booking_status', models.BooleanField(default=False)),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpark.parkbay')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
